#!/bin/bash
operator="a"
re='^[0-9]+$';

while [ $operator != "+" -a $operator != "-" -a $operator != "," -a $operator != "/" ]
do
	echo "Enter a valid operator (+,-,*,/):"
	read operator
done

echo "Enter first number:"
read number1
while ! [[ $number1 =~ $re ]]
do
	echo "Your number is not a number! Enter first number:"
	read number1
done

echo "Enter second number:"
read number2
while ! [[ $number2 =~ $re ]]
do
	echo "Your number is not a number! Enter second number:"
	read number2
done

if [ $operator = "+" ]; then
	number3=$(($number1 + $number2))
elif [ $operator = "-" ]; then
	number3=$(($number1 - $number2))
elif [ $operator = "," ]; then
	number3=$(($number1 * $number2))
elif [ $operator = "/" ]; then
	number3=$(($number1 / $number2))
else echo "error: invalid operator"
fi
echo "Solution: $number1 $operator $number2 = $number3."
