#!/bin/bash
options="Run Exit"
select option in $options; do
	if [ $option = "Run" ]; then
		echo "Hello World"
		exit
	elif [ $option = "Exit" ]; then
		echo "Exiting Now"
		exit
	else
		echo "error"
	fi
done
